version: "3"
services:
    cement:
        image: "cement:dev"
        build: 
            context: .
            dockerfile: docker/Dockerfile.dev
        hostname: cement
        stdin_open: true
        tty: true
        volumes:
            - ".:/app"
        links:
            - redis:redis
            - memcached:memcached
    docs:
        image: "cement-docs:dev"
        build: 
            context: .
            dockerfile: docker/Dockerfile.docs
        ports:
            - "8000:8000"
        volumes:
            - "./doc-new:/app"
        environment:
            BASE_URL: http://localhost:8000
    redis:
        image: redis:latest
        hostname: redis
    memcached:
        image: memcached:latest
        hostname: memcached
