baseurl = "http://builtoncement.com/"
title = "Cement Framework Documentation"
languageCode = "en-us"
theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true

toc_footers = [ 
"[![Continuous Integration Status](https://travis-ci.org/datafolklabs/cement.svg)](https://travis-ci.org/datafolklabs/cement)",
"[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/datafolklabs/cement?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)",
# "[DOCS](http://builtoncement.com/2.99/)",
# "[CODE](http://github.com/datafolklabs/cement/)",
# "[PYPI](http://pypi.python.org/pypi/cement/)",
# "[GITTER](https://gitter.im/datafolklabs/cement)",
]

# Configure the language example tabs.
[[params.language_tabs]]
key = "code"
name = "Code Examples / Usage"
# [[params.language_tabs]]
# key = "go"
# name = "Go" 
# [[params.language_tabs]]
# key = "ruby"
# name = "Ruby"
# [[params.language_tabs]]
# key = "bash"
# name = "BASH" 

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Cement Framework"
